opencompl/ssa

- SSA/WellTypedFramework.lean
I translated `Kind`s into parametric `UserType` inductives as we discussed; Lean gets pretty picky about which instance you're talking about, even with `variable`s, so the code at points becomes more messy, but in principle we should get the same just parametric on this `BaseType` with a typeclass that says we can translate to a Lean `Type`
This essentially competes with the `TypeSemantics` of Chris, where we encode the user types concretely as `Nat`s. With the instances we have in the end we could translate everything into these semantics only "under the hood".
There's an issue remaining where I couldn't figure out what was happening in the `op` case of `inferType` and sorried it now. If we agree that this approach makes sense, we can try and figure out what happened here.
> User types

- lakefile.lean
- lean-toolchain
- use the same lean version between our repo and mathlib
- do not precompile modules (it is not yet clear if this buys us anything)
> accelerate lake build

- lake-manifest.json
- lakefile.lean
- lean-toolchain
This is the last change before the following commit will break some of our proofs:
```
commit e50b7a3a8ab17894562a22aa5f6bad98c7c16cf1
Author: Chris Hughes <chrishughes24@gmail.com>
Date:   Thu Jun 8 08:15:22 2023 +0000
fix: Data/Bitvec change definition of `ofInt` to the ring homomorphism (#4525)
```
> Update mathlib to Jun 8 2023

- SSA/Core/Tactic.lean
- SSA/Projects/InstCombine/InstCombineAlive.lean
- SSA/Projects/InstCombine/InstCombineSlow.lean
- SSA/Projects/InstCombine/Tactic.lean
- Use 'simp only' to not arbitrarily simplify statements, but instead leave them for when we actually try to proof these with our automatic tacts. This is important to actually be able to see the kind of proofs we are doing before and after proofing.
- Factor simp_alive out to make sure alive specific simplifications are not polluting the global namespace.
> Polish our simp_* story

- .github/workflows/ci.yml
- SSA/Projects/InstCombine/InstCombineBase.lean
- SSA/Projects/InstCombine/Tests.lean
This has meanwhile be upstreamed to mathlib.
> alive: remove old ofInt' definition

- SSA/Projects/InstCombine/Alive.lean
- SSA/Projects/InstCombine/AliveStatements.lean
- SSA/Projects/InstCombine/Broken.lean
- SSA/Projects/InstCombine/splitandprocess.py
**Before**
```lean
∀ (w : ℕ) (a b : Bitvec w), a + (Bitvec.ofInt w 0 - b) = a - b
∀ (w : ℕ) (x C : Bitvec w), (x ^^^ Bitvec.ofInt w (-1)) + C = C - Bitvec.ofInt w 1 - x
```
**After**
```
∀ (w : ℕ) (a b : Bitvec w), a + (0 - b) = a - b
∀ (w : ℕ) (x C : Bitvec w), (x ^^^ -1) + C = C - 1 - x
```
We can already use 0/1/-1 in theorem statements, and the theorems still compile.
The only problems is ` ∀ (w : ℕ) (b : Bitvec w), b + b = Bitvec.shl b (Bitvec.toNat (Bitvec.ofInt w 1))`, which must be turned into ` ∀ (w : ℕ) (b : Bitvec w), b + b = Bitvec.shl b 1`.
Finally, it seems this change starts to break some proofs. This might be interesting to investigate.
> alive: use 0/1/-1 to simplify notation

- SSA/Experimental/Bugred/failed-to-generate-splitter-2.lean
- SSA/Experimental/Bugred/failed-to-generate-splitter.lean
- SSA/Experimental/ErasedContext.lean
- SSA/Experimental/IntrinsicAsymptotics.lean
- SSA/Projects/InstCombine/ForMathlib.lean
- lake-manifest.json
- lakefile.lean
- lean-toolchain
Express the match pattern for `matchVar` as a sequence of lets (i.e., `Lets`) together with a variable.
This removes the need for the `ExprRec` representation, thus reducing duplication and potentially opening the way to n-ary operations.
To work around a bug in Lean, this PR also changes a Context to just a list of types, instead of being `Erased`. This change is localized to just a few lines in `ErasedContext.lean`, and should be easy to revert once the bug is fixed.
> Remove expr rec

- SSA/Projects/FullyHomomorphicEncryption/Basic.lean
This PR migrates the FHE use case to the `ICom` data structure from `IntrinsicAsymptotics`. It also removes all the remaining axioms (and sorries) from the file.
> FHE New Representation

- SSA/Experimental/IntrinsicAsymptotics.lean
In adding this example, I seem to have run into a Lean bug:
```lean
-- (bollu:) unknown free variable: _kernel_fresh.104
@[reducible]
instance : OpDenote ExOp ExTy where
denote
| .cst n, _, _ => n
| .add, .cons (a : Nat) (.cons b .nil), _ => a + b
| .beq, .cons (a : Nat) (.cons b .nil), _ => a == b
| .runK (k : Nat), _, _ => (0 : Nat)
```
> feat: add example op that uses region: runK

- SSA.lean
- SSA/Core/ErasedContext.lean
- SSA/Projects/InstCombine/Base.lean
- SSA/Projects/Tensor1D/Tensor1D.lean
- SSA/Projects/Tensor2D/Tensor2D.lean
We see the dreaded error
> -- Error: unknown free variable: _kernel_fresh.459
in our instance definition
```lean
instance : OpDenote ExOp ExTy where
...
```
This suggests that we should spend the time working around
or fixing this kernel bug.
> Port Tensor1D to new framework

- SSA/Projects/InstCombine/ForStd.lean
The operations sle and slt where switched.
> alive - fix broken >= notation

- SSA/Core/Framework.lean
- SSA/Experimental/ExtrinsicAsymptotics.lean
- SSA/Experimental/ExtrinsicAsymptoticsArrays.lean
- SSA/Projects/DCE/DCE.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
- SSA/Projects/InstCombine/LLVM/Transform.lean
- SSA/Projects/InstCombine/Refinement.lean
- SSA/Projects/InstCombine/Tactic.lean
As discussed on Zulip, since the "I" stands for intrinsic from the experiments and this is not an experiment anymore at this point.
> Rename `IExpr` -> `Expr`, `ICom` -> `Com`

- SSA/Core/ErasedContext.lean
- SSA/Core/Framework.lean
- SSA/Projects/DCE/DCE.lean
- SSA/Projects/PaperExamples/PaperExamples.lean
The core issue was `Valuation.snoc_last` not applying
because one context was spelled \emptyset, while the other was spelled `[]`
By being more consistent, and introducing a simp-lemma that rewrites the former to the latter
we remove the need for `snoc'`.
> Remove `snoc'`

- SSA/Projects/FullyHomomorphicEncryption/Basic.lean
- SSA/Projects/FullyHomomorphicEncryption/Statements.lean
Goal: clear the `sorry`s for the definition of fromTensor. Pairing with @goens .
> fromTensor: full proof works, two believed sorrys are to be filled in

- SSA/Core/Framework.lean
Recall that the peephole applier tries to apply the rewrite at each program location. It uses fuel to ensure that it always terminates. This models the API that we present in the paper. 
This PR fixes the formatting of this hastily written piece of code.
This also adds the (simple) proof that the peephole applier preserves semantics, which it must, as it is built upon the lower level peephole `rewritePeepholeAt`.
> Correctness proof for fuel gated peephole rewrite applier 

- SSA/Core/ErasedContext.lean
Factored out from #128.
A derived context is a context bundled with a context difference w.r.t. a static base context.
This makes it easy to define coercions from variables of the base context into the derived context.
> feat: add derived contexts

- SSA/Projects/InstCombine/Base.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
A refactor to clean up some of the EDSL code that got merged in #128.
By adding a bit more structure to the `MOp` type, we can greatly reduce the LOC we need in EDSL, by consolidating a bunch of carbon-copy match arms into just one.
Also, I've removed `mkOpExpr` since it did not seem to be used anywhere.
> Edsl cleanup refactor

- SSA/Core/ErasedContext.lean
- SSA/Core/Framework.lean
- SSA/Projects/Scf/Scf.lean
Adjacent for loops can be fused, assuming that the second loop ends where the first one starts.
> Scf for fusion

- SSA/Core/ErasedContext.lean
- SSA/Projects/InstCombine/Base.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
Attempt at fixing some of the alive examples that are currently not working.
Mostly dumping this here in case anyone wants to have a look next week.
The most usable parts so far are the extra recursion principles for `Ctxt` and `Ctxt.Valuation`: I hope to replace the current `generalize ...` trick with a bit of meta code that analyzes the type of a `Ctxt.Valuation`, recursively applies the case distinction until the remaining context is empty, and then reduces the `(Ctxt.Valuation.snoc _ v) (Var.last ..)` to just `v` --- we have a simp-lemma that should do this rewrite, but it somehow fails to unify with the lhs correctly, this might be a job for `simproc`.
> feat: recursion principles for contexts and valuations

- SSA/Projects/InstCombine/LLVM/Semantics.lean
This makes the LLVM semantics agree precisely with our definitions.
> feat: fix bitwidth to a single width across args and return value

- SSA/Core/Framework.lean
These commits were marked 'for Mathlib' but are not used anymore in the Framework formalization. Let's drop them to keep the file focused.
> Remove unused theorems

- SSA/Projects/InstCombine/Tactic.lean
These concepts should already have been eliminated in simp_peephole.
> Remove SSA tactics from simp_alive_peephole

- SSA/Projects/InstCombine/LLVM/Semantics.lean
- SSA/Projects/InstCombine/LLVM/SimpSet.lean
- SSA/Projects/InstCombine/Tactic.lean
This simp set will make our simp_alive_peephole tactic simpler.
> chore: introduce simp set for llvm

- SSA/Core/Tactic.lean
- SSA/Projects/InstCombine/Tactic.lean
If we do not need special simp options, we should probably stick to the default options as much as possible or document why we use different options. These two options look as if they potentially increase the computational cost of simp. As our current tests pass without them, we remove them for now. We can always add them back if we find a test case that would require them. We keep `decide := false` for now, as this seems to be a performance optimization.
> chore: remove unused simp options

- SSA/Core/HVector.lean
- SSA/Core/Tactic.lean
- SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
- SSA/Projects/InstCombine/Base.lean
- SSA/Projects/InstCombine/LLVM/Semantics.lean
- SSA/Projects/InstCombine/LLVM/SimpSet.lean
- SSA/Projects/InstCombine/Tactic.lean
We introduce with `LLVM.<op>` a set of formal definitions of the per-operation semantics for the LLVM dialect that must be unfolded with `simp_llvm_option` before the per-operation semantics are exposed. This allows us to introduce a tactic `simp_alive_ssa`, which eliminates only the overhead of SSA and leaves us with explicit statements about the not-yet-unfolded LLVM operation semantics.
> feat: hide monadic behavior of llvm semantics behind a function boundary.

- SSA/Projects/InstCombine/ComWrappers.lean
These wrappers allow us to easily write `Com` programs without going through the MLIR parsing. Here an example:
```lean
def test (w : ℕ) :
Com InstCombine.Op [InstCombine.Ty.bitvec w] (InstCombine.Ty.bitvec w) :=
.lete (const  w 0  ) <|
.lete (not    w 0  ) <|
.lete (neg    w 0  ) <|
.lete (and    w 0 0) <|
.lete (or     w 0 0) <|
.lete (xor    w 0 0) <|
.lete (shl    w 0 0) <|
.lete (lshr   w 0 0) <|
.lete (ashr   w 0 0) <|
.lete (sub    w 0 0) <|
.lete (add    w 0 0) <|
.lete (mul    w 0 0) <|
.lete (sdiv   w 0 0) <|
.lete (udiv   w 0 0) <|
.lete (srem   w 0 0) <|
.lete (urem   w 0 0) <|
.lete (icmp   w .eq 0 0) <|
.lete (select w 0 1 1) <|
.ret ⟨0, by simp [Ctxt.snoc]⟩
```
This change was extracted from https://github.com/opencompl/ssa/pull/167. Compared to #167 the new implementation …
> feat: add alive com wrappers

- SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
- SSA/Projects/InstCombine/LLVM/Semantics.lean
- SSA/Projects/InstCombine/Tactic.lean
We previously unfolded binds too eagerly, which led to unnecessary complex proof states such as:
```lean
⊢ ∀ (e e_1 : Option (BitVec w)),
(match
match e_1, fun x' =>
match e, fun y' => some (x' &&& y') with
| none, x => none
| some a, b => b a with
| none, x => none
| some a, b => b a,
fun x' =>
match e, fun y' => some (x' &&& y') with
| none, x => none
| some a, b => b a with
| none, x => none
| some a, b => b a) ⊑
match e_1, fun x' =>
match e, fun y' => some (x' &&& y') with
| none, x => none
| some a, b => b a with
| none, x => none
| some a, b => b a
```
After this patch this is turned into:
```lean
⊢ ∀ (e e_1 : Option (BitVec w)),
(do
let x ← e_1
let x_1 ← e
let y' ← e
pure (x &&& x_1 &&& y')) ⊑
do
let x' ← e_1
let y' ← e
pure (x' &&& y')
```
This is a lot more readable.
The reduced …
> feat: do not unfold binds in alive_* tactics

- SSA/Projects/InstCombine/Tactic.lean
This is factored out from https://github.com/opencompl/ssa/pull/191 to minimize the diff to main.
> chore: drop unnecessary open

- SSA/Projects/FullyHomomorphicEncryption/Basic.lean
This peels code from the mega PR https://github.com/opencompl/ssa/pull/196 into the first bite sized chunk, where we introduce the `OpDenote` instance.
> feat: add Op.denote as a OpDenote instance for FHE

- SSA/Projects/FullyHomomorphicEncryption.lean
- SSA/Projects/FullyHomomorphicEncryption/Basic.lean
- SSA/Projects/FullyHomomorphicEncryption/Rewrites.lean
- SSA/Projects/FullyHomomorphicEncryption/Syntax.lean
This adds a new `[fhe_com |...]`, mimicking the `[alive_com|...]`, that provides a prettier syntax to write FHE examples in.
---
Code peeled from pre-paper submission PR: https://github.com/opencompl/ssa/pull/196.
Code stacked on: https://github.com/opencompl/ssa/pull/230.
> feat: Implement [fhe_com |...] to write FHE examples with sugar.

- SSA/Projects/FullyHomomorphicEncryption/Rewrites.lean
- SSA/Projects/FullyHomomorphicEncryption/Syntax.lean
To make this example work, we need a definition of `R.ofZ` that is computable, and which is not agressively unfolded. This is ensured by our `axiom` trick.
Code peeled from pre-paper submission PR: https://github.com/opencompl/ssa/pull/196.
Code stacked on: https://github.com/opencompl/ssa/pull/234
---
Closes https://github.com/opencompl/ssa/pull/196 (This PR fully integrates the features of https://github.com/opencompl/ssa/pull/196 into main.)
> feat: add example from paper for FHE.

- SSA/Core/MLIRSyntax/EDSL.lean
- SSA/Projects/FullyHomomorphicEncryption/Syntax.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
- SSA/Projects/PaperExamples/PaperExamples.lean
Define a generic term elaborator `elabIntoCom`, which can be used to easily define dialect-specific term elaborators. For example, if `FooOp` is the type of operations of a "Foo" dialect, we can build a term elaborator for this dialect as follows:
```
elab "[foo_com| " reg:mlir_region "]" : term => SSA.elabIntoCom reg q(FooOp)
--     ^^^^^^^                                                        ^^^^^
```
This notably doesn't work for the Alive/LLVM dialect, since we have to figure out what to do with meta variables. I've tried to make that work, but it's quite complicated, so I'd like to merge the easier case first.
>   refactor: introduce a generic building block for dialect edsl

- SSA/Projects/FullyHomomorphicEncryption/Rewrites.lean
- SSA/Projects/FullyHomomorphicEncryption/Syntax.lean
Closes https://github.com/opencompl/ssa/issues/240
https://github.com/opencompl/ssa/pull/239 toned down how aggressive our unfolding is (to be Reducibility.default) [thanks @alexkeizer !], Thus, we can now use `irreducible_def` to hide the implementation of `R.ofZComputable`. This eliminates our reliance on axioms.
This generally improves the trustworthiness of our development.
> chore: remove use of axiom in FHE that was a workaround for aggressive reducibility

- SSA/Core/Tactic.lean
These were added in 121e9c7fa316edf8fc1824da136cb6a2cb3ba08c in an attempt to reduce the delta of the FHE branch, but were really not needed.
> chore: drop two unnecessary lemmas from simp_peephole

- SSA/Core/MLIRSyntax/EDSL.lean
- SSA/Core/Tactic.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
This PR uses `elabIntoCom` to simplify the definition of `alive_com`. This means first `elabIntoCom` will normalize the `Com` (which still has object metavariables), and only afterwards do we instantiate the metavariables and reduce it *again*.
To reduce the impact of this double reduction, we also weaken the reduction done by `elabIntoCom` analogously to `ctxtNf`; we recursively call `whnf` on the body of a `Com.lete`, instead of fully reducing. This is enought for `FHE` and `PaperExamples`. Alive, however, does need full reduction to get rid of the meta-var instantiation code, so the second reduction in `alive_com` is still `reduce`.
Minor testing suggests this version of `alive_com` is still faster than what we currenlty have in main: `and_sequence_30_lhs` (of `ScalingTest`) in the …
> change: redefine alive dsl in terms of generic `elabIntoCom`

- SSA/Core/Framework.lean
- SSA/Core/Tactic.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
RegionSignature.map and Signature.map. This makes proof states easier to read, and allows for unfolding one of the instances of Functor.map at a time.
This is pulled out of https://github.com/opencompl/ssa/pull/225 as an independent useful change.
Co-authored-by: Siddharth Bhat <siddu.druid@gmail.com>
> Change our use of Functor.map (via <$>) to a more targeted use of ..

- SSA/Projects/InstCombine/Base.lean
- SSA/Projects/InstCombine/LLVM/Enumerator.lean
- SSA/Projects/InstCombine/LLVM/Semantics.lean
This change ensures that simp_alive_ssa does not unfold the type definition of LLVM bitvectors, such that our semantics do not leak before we unfold them.
> feat: do not leak the type definition in alive

- SSA/Projects/InstCombine/Alive.lean
- SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean
This proof is factored out of https://github.com/opencompl/ssa/pull/167 and is part of a collection of proofs that we manually wrote to demonstrate the status of leans automation in BitVectors and such.
> feat: upstream a handwritten proof for alive - alive_DivRemOfSelectLarge proofs one

- SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean
- SSA/Projects/InstCombine/ForLean.lean
- SSA/Projects/InstCombine/LLVM/Semantics.lean
This one is again pulled out from https://github.com/opencompl/ssa/pull/167.
> feat: handwritten-proof AndOrXor

- SSA/Projects/InstCombine/ForLean.lean
Avoid including 'Tactic.lean' as this pulls in Refinement.lean, which currently pollutes the refinement relation and prevents the use of ForLean.lean in AliveStatements.
> chore: reduce imports

- .github/workflows/ci.yml
- SSA/Core/MLIRSyntax.lean
- SSA/Core/MLIRSyntax/GenericParser.lean
- SSA/Core/MLIRSyntax/Parser.lean
- SSA/Projects/InstCombine/LLVM/Opt.lean
- SSA/Projects/InstCombine/LLVM/Parser.lean
- lakefile.lean
- test/LLVMDialect/InstCombine/bb0.mlir
This adds an entry point to parse MLIR code and execute it via our denotational semantics.
> feat: implement 'opt' entrypoint to parse MLIR from files. (#102)

- SSA/Core/Framework.lean
- SSA/Core/MLIRSyntax/GenericParser.lean
- SSA/Experimental/MatchGoal.lean
- SSA/Projects/CSE/CSE.lean
- SSA/Projects/InstCombine/ForLean.lean
- SSA/Projects/PaperExamples/PaperExamples.lean
This cleans up our CI output significantly.
> chore: guard all #print,#reduce,#eval with #guard_msgs in GenericParser.lean

- SSA/Core/Framework.lean
This ensures that our core proofs do not depend on sorryAx.
> chore: add guard_msgs for axioms of core theorems

- SSA/Core/ErasedContext.lean
- SSA/Core/Util/ConcreteOrMVar.lean
These theorems will allow us to reason about the context and MVar with less unfolding about low-level theorems. While uses of these theorems are still worked on, the theorems seem to be generally useful so lets upstream them already to keep later patches small.
Co-Authored-By : Siddharth Bhat<siddu.druid@gmail.com>
These are factored out of https://github.com/opencompl/ssa/pull/225.
> feat: theorems about Ctxt and MVar

- SSA/Projects/InstCombine/AliveStatements.lean
- SSA/Projects/InstCombine/update_alive_statements.py
https://github.com/opencompl/ssa/pull/225 will fix three statements, one of which will introduce multiple goals in `AliveStatements.lean`. This PR makes `AliveStatements.lean` robust against multiple worries by using `all_goals`.
Thank you @alexkeizer for proposing this.
> core: make AliveStatements.lean robust against multiple goals

- SSA/Projects/InstCombine/ForLean.lean
This ensures that the theorem solves our theorem in AliveStatements.lean. This brings us from 50 to 51 proven lemma.
> chore: express lemma in terms of '+' instead of .add

- SSA/Projects/InstCombine/ForLean.lean
This solves one AliveStatement
> feat: add BitVec.and_add_xor_eq_or

- SSA/Projects/FullyHomomorphicEncryption/Basic.lean
The FHE file used both ℤ and `Int` as symbols. Unify to `Int`.
> Unify Nat/Int in  FHE

- SSA/Core/Tactic.lean
This meta-code breaks with the next lean update. As it is unused, we drop it beforehand.
> chore: remove unused change_mlir_context

- SSA/Projects/InstCombine/LLVM/CLITests.lean
- SSA/Projects/Scf/ScfFunctor.lean
These changes issues in the 4.9 update. As they are independent and should pass CI already, we factored these out.
> chore: add missing def to simp set and use full types (prepare for lean 4.9)

- SSA/Projects/InstCombine/ForLean.lean
- SSA/Projects/InstCombine/LLVM/SimpSet.lean
- SSA/Projects/InstCombine/TacticAuto.lean
This solves one additional theorems and simplifies a number of theorems we are seeing. We are now at 50/93 solved statements.
> feat: eliminate sequences of BitVec.ofBool

- SSA/Projects/InstCombine/Tactic.lean
This is helpful for debugging, when we copy the individual statements to the actual proof, which may not have Ctxt open.
> chore: use full context in simp_alive_meta

- SSA/Core/ErasedContext.lean
- SSA/Core/Framework.lean
- SSA/Projects/InstCombine/Tactic.lean
- SSA/Projects/InstCombine/Test.lean
The use of reduce in the meta programming framework has made the frontend pretty fragile. We build now step-by-step the simp lemmas needed to simplify the eDSL away such that reduce can eventually be dropped.
This change is needed to enable the lean 4.9.0 update.
Co-authored-by: Alex Keizer <alex@keizer.dev>
Co-authored-by: Siddharth Bhat <siddu.druid@gmail.com>
> feat: make LLVM eDSL work without reduce - one instruction case

- SSA/Projects/InstCombine/Test.lean
For some reason the parser accepts this syntax. We should look into this at some point.
> chore: fix syntax in test cases

- SSA/Core/ErasedContext.lean
Before this change toSnoc and toMap could not be distinguished visually, which made debugging unnecessarily hard. Also, we really want to eliminate toMap to ensure that all meta-abstractions are liminated before we try to remove the SSA semantics.
> chore: do not make Ctxt.Var.toMap a coercion

- SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
- SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean
- SSA/Projects/InstCombine/AliveStatements.lean
- SSA/Projects/InstCombine/ForLean.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
- SSA/Projects/InstCombine/TacticAuto.lean
This change is needed to update to lean 4.9. We commit this as a separate change, such that for future debugging sessions there is a commit where easily both versions can be inspected.
> chore: disable reduction in LLVM eDSL

- SSA/Core/MLIRSyntax/GenericParser.lean
This changes various parts of the MLIR generic parser to inspect the `rawVal` of an identifier, rather than the `val`. This raw value is literally the substring of the input value that corresponds to the identifier, and is thus not affected by hygiene.
This becomes especially relevant if we want to generate MLIR syntax with macros, since we don't want our types and attributes, which use identifiers in the parser, to be affected by hygiene. In particular, this patch removes the need for a `set_option hygiene false` in #359
> Fix: Make the generic MLIR parser hygiene resistant

- SSA/Core/MLIRSyntax/GenericParser.lean
- SSA/Projects/InstCombine/LLVM/PrettyEDSL.lean
This fixes an issue raised in #369, where the constant `-1` failed to parse in the concise syntax.
In the process, the generic edsl was also changed so that constant without type ascription are always assumed to be signless (rather than the type depending on whether the value is negative or not).
> feat: support negative constants in the pretty edsl

- SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
- SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean
- SSA/Projects/InstCombine/AliveStatements.lean
- SSA/Projects/InstCombine/ForMathlib.lean
- SSA/Projects/InstCombine/LLVM/PrettyEDSL.lean
- SSA/Projects/InstCombine/ScalingTest.lean
- SSA/Projects/InstCombine/Tactic.lean
- SSA/Projects/InstCombine/TacticAuto.lean
- SSA/Projects/InstCombine/Test.lean
- SSA/Projects/InstCombine/TestLLVMOps.lean
- SSA/Projects/InstCombine/update_alive_statements.py
- SSA/Projects/PaperExamples/PaperExamples.lean
We convert all manually written users of the LLVM syntax to the pretty syntax but leave the AliveAutogenerated.lean for a later conversion to allow the auto-generation to be updated together with AliveAutoGenerated.lean.
We also add support for llvm.icmp, which requires separate macro rules to support its i1 return type.
> feat: convert to llvm pretty and support for llvm.icmp

- SSA/Projects/InstCombine/AliveAutoGenerated.lean
This is factored out of https://github.com/opencompl/ssa/pull/369 and demonstrates that the actual syntax works. In a subsequent change, we need to auto-update the file via alive.
The following script was used for the update:
```bash
export FILES="AliveAutoGenerated.lean"
(cd SSA/Projects/InstCombine/; sed -e 's/LLVM.EDSL/LLVM.PrettyEDSL/' -i $FILES)
(cd SSA/Projects/InstCombine/; sed -e 's/= "\(llvm.mlir.constant\)" () { value = \(.*\) :\(.*\) } :() -> \(.*\)/= \1 \2 : \3/' -i $FILES)
(cd SSA/Projects/InstCombine/; sed -e 's/= "\(llvm.select\)" (\(.*\),\(.*\), \(.*\)) : (.*, \(.*\), .*) -> (.*)/= \1 \2, \3, \4 : \5/' -i $FILES)
(cd SSA/Projects/InstCombine/; sed -e 's/= "\(llvm..*\)" (\(.*\),\(.*\)) : (\(.*\),.*) -> .*/= \1 \2, \3 : \4/' -i $FILES)
(cd SSA/Projects/InstCombine/; sed -e …
```
> feat: move AliveAutogenerated to concise syntax - sed part

- SSA/Projects/InstCombine/AliveAutoGenerated.lean
- SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
- SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean
- SSA/Projects/InstCombine/LLVM/EDSL.lean
- SSA/Projects/InstCombine/LLVM/PrettyEDSL.lean
- SSA/Projects/InstCombine/ScalingTest.lean
- SSA/Projects/InstCombine/Test.lean
We mixed alive and llvm and used them overall inconsistently. The llvm dialect syntax really is not specific to alive. Hence, let's rename it to llvm.
> chore: rename alive_icom to llvm

- SSA/Core/MLIRSyntax/GenericParser.lean
- SSA/Projects/InstCombine/LLVM/PrettyEDSL.lean
Implements pretty quasiquotations for the LLVM dialect, so that we can write:
```lean
$v0 = llvm.mlir.constant ${2**n}
```
where `n` is a Lean variable
> fix: antiquotations in pretty syntax
