opencompl/ssa

SSA/Examples/Arith.lean, SSA/Examples/InstCombine.lean, SSA/Examples/InstCombineBase.lean, SSA/Examples/InstCombinePeepholeRewrites.lean, SSA/Framework.lean, SSA/Util.lean, SSA/WellTypedFramework.lean, lake-manifest.json, lakefile.lean, lean-toolchain
With performance issues, but this does `simp` very nicely thanks to @ChrisHughes24's framework! I think it's worth merging (and looking into the performance and more examples later)
=> InstCombine Example

SSA/Framework.lean
This simplifies some expressions.
=> Move [Region]Var to Int (from Nat)

SSA/Projects/InstCombine/ForMathlib.lean
Allows us to properly state the theorems for UB
=> Define a Refinement relation

SSA/Core/Util.lean, SSA/Projects/InstCombine/ForMathlib.lean, SSA/Projects/InstCombine/InstCombineAlive.lean, SSA/Projects/InstCombine/InstCombineAliveStatements.lean, SSA/Projects/InstCombine/InstCombineBase.lean
Push the `Option` into the denotation of the UserType for UB in Alive
=> Option bitvec

SSA.lean, SSA/Core/WellTypedFramework.lean, SSA/Projects/Tensor2D/Tensor2D.lean
=> add tensor2d theorems

SSA/Core/Tactic.lean, SSA/Projects/InstCombine/Broken.lean, SSA/Projects/InstCombine/ForMathlib.lean, SSA/Projects/InstCombine/InstCombineAlive.lean, SSA/Projects/InstCombine/InstCombineAliveStatements.lean, SSA/Projects/InstCombine/InstCombineBase.lean, SSA/Projects/InstCombine/extract_alive_statements.sh
more alive rewrites, and some broken ones (in a separate file)
=> More alive

lake-manifest.json, lakefile.lean, lean-toolchain
This includes improved notation for Bitvec
=> Update mathlib to June 21

SSA/Projects/InstCombine/Broken.lean, SSA/Projects/InstCombine/ForMathlib.lean, SSA/Projects/InstCombine/InstCombineAlive.lean, SSA/Projects/InstCombine/InstCombineAliveStatements.lean, SSA/Projects/InstCombine/InstCombineBase.lean, SSA/Projects/InstCombine/Tactic.lean, SSA/Projects/InstCombine/extract_alive_statements.sh, lake-manifest.json, lakefile.lean
- Upgrade to mathlib commit that has the instances
- define custom notation for sshr
- extend simp_alive tactic to remove some lingering `mapM`s
- update generation scripts and generated files
=> Add shl/shr operators

SSA/Experimental/ExtrinsicAsymptotics.lean, SSA/Experimental/IntrinsicAsymptotics.lean
Commented results of some experiments with @tobiasgrosser and @ChrisHughes24
=> Investigations on asymptotics of program encodings

SSA/Experimental/HVector.lean, SSA/Experimental/IntrinsicAsymptotics.lean
Add first draft of regions into the IR.
=> Chris add regions

SSA.lean, SSA/Projects/Holor/Holor.lean
We have basic algebra instances now, so it would be nice to have this in-tree.
What we do with this would be good to figure out. I can extend the API to support almost all the operations listed in the file. The only nit that I can see is things like `-inf`, which we don't have since we don't have a model of floating point. 
There is the question of what will give us most bang for buck, in terms of time spent developing. I feel @tobiasgrosser has thoughts on this.
If we want to prove theorems, then I need someone's help t find interesting theorems about these objects.
=> Pull in Holor development

SSA/Core/Context.lean, SSA/Core/ErasedContext.lean, SSA/Core/Framework.lean, SSA/Core/Tactic.lean, SSA/Core/Util/ConcreteOrMVar.lean, SSA/Experimental/Bugred/failed-to-generate-splitter-2.lean, SSA/Experimental/Bugred/failed-to-generate-splitter.lean, SSA/Experimental/Bugred/slow-dependent-pattern-matching-string.lean, SSA/Experimental/FlatSSAEncoding.lean, SSA/Projects/FullyHomomorphicEncryption/Basic.lean, SSA/Projects/Holor/Holor.lean, SSA/Projects/InstCombine/Base.lean, SSA/Projects/InstCombine/ForStd.lean, SSA/Projects/InstCombine/Test.lean, SSA/Projects/InstCombine/Tests.lean, SSA/Projects/MLIRSyntax/AST.lean, SSA/Projects/MLIRSyntax/EDSL.lean, SSA/Projects/Tensor1D/Tensor1D.lean, SSA/Projects/Tensor2D/Tensor2D.lean
This makes sure other PRs are not polluted by whitespace noise.
=> Remove all trailing whitespaces in SSA/

SSA/Projects/InstCombine/ForStd.lean
- Simplify code
- Make sure code lives in Std.BitVec namespace
=> Alive ForStd: polish code

SSA/Projects/InstCombine/AliveStatements.lean, SSA/Projects/InstCombine/Base.lean, SSA/Projects/InstCombine/LLVM/Semantics.lean
@goens can you remind me how one regenerates the theorem statements?
=> feat: fix select semantics to lazily evaluate arguments

SSA.lean, SSA/Projects/Scf/ScfFunctor.lean
This is work in progress, and help debugging would be appreciated.
=> feat: add functorial version of scf

SSA/Core/Tactic.lean
This option is in the default options since some lean releases.
=> chore: do not set decide := false in simp

SSA/Core/Tactic.lean, SSA/Projects/InstCombine/AliveAutoGenerated.lean, SSA/Projects/InstCombine/AliveHandwrittenExamples.lean
This superseeds https://github.com/opencompl/ssa/pull/168.
=> feat: make our generalize trick work for arbitrary number of variables

SSA/Core/Tactic.lean
=> chore: document `simp_peephole` more thoroughly.

SSA/Projects/InstCombine/Alive.lean, SSA/Projects/InstCombine/ComWrappers.lean
And fix it with respect to the recent dialect introduction.
=> chore: include InstCombine wrappers in build

SSA/Core/Util.lean
This avoids a warning about the deprecated Std.BitVec
=> chore: drop some dead code

SSA/Projects/InstCombine/ComWrappers.lean, SSA/Projects/InstCombine/LLVM/SimpSet.lean
This is extracted out of https://github.com/opencompl/ssa/pull/167.
=> Add a simp set to unwrap the com wrappers

SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean, SSA/Projects/InstCombine/ForLean.lean
This one is again pulled out from https://github.com/opencompl/ssa/pull/167
=> feat: upstream alive_simplifyMulDivRem290

SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean, SSA/Projects/InstCombine/ForLean.lean, SSA/Projects/InstCombine/LLVM/Semantics.lean
Peeled from https://github.com/opencompl/ssa/pull/167/
=> wip: MulDivRem805

SSA/Projects/InstCombine/Alive.lean, SSA/Projects/InstCombine/ForLean.lean, SSA/Projects/InstCombine/LLVM/Lemmas.lean
Closes https://github.com/opencompl/ssa/issues/152, https://github.com/opencompl/ssa/issues/153, https://github.com/opencompl/ssa/issues/154, supercedes #160
=> wip: Formalize muldivrem, select, andorxor 

SSA.lean, SSA/Core.lean, SSA/Core/MLIRSyntax.lean
This cleans up our import story.
=> feat: include SSA/Core.lean and add SSA/Core/MLIRSyntax.lean

.github/workflows/ci.yml, SSA/Core/MLIRSyntax.lean, SSA/Core/MLIRSyntax/GenericParser.lean, SSA/Core/MLIRSyntax/Parser.lean, SSA/Projects/InstCombine/LLVM/Opt.lean, SSA/Projects/InstCombine/LLVM/Parser.lean, lakefile.lean, test/LLVMDialect/InstCombine/bb0.mlir
This adds an entry point to parse MLIR code and execute it via our denotational semantics.
=> Cli entry point

SSA/Projects/InstCombine/TacticAuto.lean
This gives us 48 out of 90 statements proven (42 sorry-ed).
=> Optimize the kernels in AliveStatements

SSA/Projects/InstCombine/update_alive_statements.py
This should speedup the CI a bit.
=> feat: run update_alive_statements in parallel

.github/workflows/doc.yml
@tobiasgrosser any idea how to run the doc CI action on this PR?
=> chore: fix doc path to .lake/build/doc

lakefile.lean
This is in preparation for considering moving to the lakefile TOML format.
=> chore: cleanup lakefile

SSA/Projects/InstCombine/Alive.lean, SSA/Projects/InstCombine/Test.lean
This fixed https://github.com/opencompl/ssa/issues/334.
=> chore: fix tests

SSA/Projects/InstCombine/LLVM/EDSL.lean
Co-authored-by: Siddharth Bhat <siddu.druid@gmail.com>
=> feat: make reduction in alive EDSL configurable

SSA/Projects/InstCombine/ForLean.lean
I commented the Mathlib import at the top and started fixing lemmas. There are still plenty more that need fixing, so we do this step-by-step.
=> Remove references to mathlib

SSA/Core/MLIRSyntax/GenericParser.lean
=> Revert "Fix: Make the generic MLIR parser hygiene resistant"

SSA/Projects/InstCombine/LLVM/PrettyEDSL.lean
The diff is a bit larger than I'd like, because I had to move the `macro`s back to `macro_rules`, since the former doesn't handle optional syntax particularly well (see [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Pass.20optional.20syntax.20in.20macro/near/442254013))
=> feat: support leaving out type annotations in LLVM's pretty EDSL

SSA/Projects/InstCombine/LLVM/EDSL.lean, SSA/Projects/InstCombine/Test.lean
This prepares for the update to lean 4.9.0
=> chore: drop reduce in LLVM EDSL

SSA/Core/Examples.lean, SSA/Core/Framework.lean, SSA/Core/MLIRSyntax/EDSL.lean, SSA/Core/MLIRSyntax/Transform.lean, SSA/Core/Tactic.lean, SSA/Projects/CSE/CSE.lean, SSA/Projects/DCE/DCE.lean, SSA/Projects/FullyHomomorphicEncryption/Rewrites.lean, SSA/Projects/InstCombine/AliveHandwrittenLargeExamples.lean, SSA/Projects/InstCombine/ComWrappers.lean, SSA/Projects/InstCombine/LLVM/CLITests.lean, SSA/Projects/InstCombine/Tactic.lean, SSA/Projects/InstCombine/Test.lean, SSA/Projects/PaperExamples/PaperExamples.lean, SSA/Projects/Scf/ScfFunctor.lean
This addresses https://github.com/opencompl/ssa/issues/382.
=> chore: rename lete to var to match paper

SSA/Core/Framework.lean
This will facilitate the lean 4.9 update
=> chore: avoid freestanding simp lemmas in Framework
